services:
  - type: web
    name: telegram-bot
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python main.py"
    envVars:
      - key: TELEGRAM_TOKEN
        value: "7612146240:AAFyiH0owMGJWQ8UYrE5fnK7roYccg0cTq0"  # Your bot token
      - key: CHANNEL_LINK
        value: "https://t.me/+LQPqGKJWktk2NDFk"  # Your Telegram channel link
    autoDeploy: true
    healthCheckPath: "/"
