services:
  - type: web
    name: telegram-bot
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python main.py"
    envVars:
      - key: TELEGRAM_TOKEN
        value: "7906386980:AAEzysWsp0bvI7doUbpz5Q2OGN280J1Rz2A"  # Your bot token
      - key: CHANNEL_LINK
        value: "https://t.me/+j6JaiV_W5k5iZTRl"  # Your Telegram channel link
    autoDeploy: true
    healthCheckPath: "/"
