version: 1
services:
  - type: web
    name: telegram-bot
    env: python
    plan: free
    runtime: python3
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python bot.py"
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        value: "7970351713:AAH37a7sXeLODhk5lE-Kv-rHZfT5rf27z"  # You can also set this in Render dashboard
